version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root@123
    ports:
      - 3306:3306

  db-adminer:
    image: adminer
    ports:
      - 8080:8080