version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root@123
    ports:
      - 3306:3306
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql
  redis:
    image: redis
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./docker/volumes/redis:/data
  server:
    build: ./server
    ports:
      - 8000:8000
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/sem4_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root@123
      - SPRING_REDIS_HOST=redis
    volumes:
      - ./docker/volumes/server/uploads:/uploads
    depends_on:
      - db
      - redis
  ui:
    build: ./ui
    ports:
      - 80:80
    environment:
      - WS_ENDPOINT=ws://server:8000/ws
      - API_ENDPOINT=http://server:8000/api