version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root@123
    ports:
      - 33060:3306
    volumes:
      - db:/var/lib/mysql
  redis:
    image: redis
    command: redis-server --appendonly yes
    ports:
      - 63790:6379
    volumes:
      - redis:/data
  server:
    build: ./server
    ports:
      - 8000:8000
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/sem4_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root@123
      - SPRING_REDIS_HOST=redis
    volumes:
      - server:/uploads
    depends_on:
      - db
      - redis
  ui:
    build: ./ui
    ports:
      - 88:80
volumes:
  db:
  redis:
  server: